<?php

namespace ContainerAkWJ5Bp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TSouDIuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TSouDIu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TSouDIu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['privates', '.errored.iZJ2ICk', NULL, 'Cannot determine controller argument for "App\\Controller\\AdminController::clients()": the $doctrine argument is type-hinted with the non-existent class or interface: "App\\Controller\\ManagerRegistry". Did you forget to add a use statement?'],
        ], [
            'doctrine' => '?',
        ]);
    }
}
