<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBeCxSdp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBeCxSdp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBeCxSdp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBeCxSdp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBeCxSdp\App_KernelDevDebugContainer([
    'container.build_hash' => 'BeCxSdp',
    'container.build_id' => 'd2128288',
    'container.build_time' => 1706091051,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBeCxSdp');
