<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD8xF0Ts\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD8xF0Ts/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD8xF0Ts.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD8xF0Ts\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD8xF0Ts\App_KernelDevDebugContainer([
    'container.build_hash' => 'D8xF0Ts',
    'container.build_id' => 'ca9cff91',
    'container.build_time' => 1706034266,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD8xF0Ts');
