<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOlO7Sh6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOlO7Sh6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOlO7Sh6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOlO7Sh6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOlO7Sh6\App_KernelDevDebugContainer([
    'container.build_hash' => 'OlO7Sh6',
    'container.build_id' => '1a63dba0',
    'container.build_time' => 1704988841,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOlO7Sh6');
